---
- name: delete an instance
  gcp_compute_instance:
    name: webserver1
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    state: absent

- name: delete an address
  gcp_compute_address:
    name: webserver1-address
    region: "{{ region }}"
    project: "{{ gcp_project }}"
    state: absent

- name: delete a firewall
  gcp_compute_firewall:
    name: ansible-firewall
    project: "{{ gcp_project }}"
    state: absent

- name: delete a network
  gcp_compute_network:
    name: ansible-network
    project: "{{ gcp_project }}"
    state: absent
