---
- name: create a disk
  gcp_compute_disk:
    name: 'compute-disk'
    size_gb: 50
    source_image: 'projects/centos-cloud/global/images/centos-7-v20190116'
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
    - https://www.googleapis.com/auth/compute
    state: present
  register: disk

- name: create a network
  gcp_compute_network:
    name: 'compute-network'
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
    - https://www.googleapis.com/auth/compute
    state: present
  register: network

- name: create a address
  gcp_compute_address:
    name: 'compute-address'
    region: "{{ region }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
    - https://www.googleapis.com/auth/compute
    state: present
  register: address

- name: create a firewall
  gcp_compute_firewall:
    name: 'compute-firewall'
    network: "projects/{{ gcp_project }}/global/networks/ansible-network-instance"
    allowed:
    - ip_protocol: tcp
      ports:
      - '80'
    - ip_protocol: tcp
      ports:
      - '22'
    target_tags:
    - 'apache-http-server'
    source_ranges: ['0.0.0.0/0']
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
    - https://www.googleapis.com/auth/compute
    state: present
  register: firewall

- name: create a instance
  gcp_compute_instance:
    state: present
    name: compute-instance
    machine_type: n1-standard-1
    disks:
    - auto_delete: true
      boot: true
      source: "{{ disk }}"
    network_interfaces:
    - network: "{{ network }}"
      access_configs:
      - name: 'External NAT'
        nat_ip: "{{ address }}"
        type: 'ONE_TO_ONE_NAT'
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
    - https://www.googleapis.com/auth/compute
    tags:
      items:
      - 'apache-http-server'
  register: instance

- name: add host to groupname
  add_host:
    hostname: "{{ address.address }}"
    groups: new_instances
