---
- name: Create GCP resources
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    gcp_project: ansible-gce-demo
    gcp_cred_kind: serviceaccount
    gcp_cred_file: '~/Documents/Personal/gcp_creds/ansible-gce-demo-a0dbb4ac2ff7.json'
    zone: us-east1-b
    region: us-east1
    scopes:
    - https://www.googleapis.com/auth/compute

  tasks:
  - name: create a network
    gcp_compute_network:
      name: compute-network
      auto_create_subnetworks: yes
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes: "{{ scopes }}"
      state: present
    register: network

  - name: create a subnetwork
    gcp_compute_subnetwork:
      name: compute-subnet
      region: "{{ region }}"
      network: "{{ network }}"
      ip_cidr_range: 172.16.0.0/28
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes: "{{ scopes }}"
      state: present
    register: subnet

  - name: create an address
    gcp_compute_address:
      name: compute-address
      region: "{{ region }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes: "{{ scopes }}"
      state: present
    register: address

  - name: create a firewall
    gcp_compute_firewall:
      name: compute-firewall
      network: "projects/{{ gcp_project }}/global/networks/{{ network.name }}"
      allowed:
      - ip_protocol: tcp
        ports:
        - 80
      - ip_protocol: tcp
        ports:
        - 22
      target_tags:
      - apache-http-server
      source_ranges: ['0.0.0.0/0']
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes: "{{ scopes }}"
      state: present
    register: firewall

  - name: create a disk
    gcp_compute_disk:
      name: compute-disk
      size_gb: 200
      source_image: 'projects/centos-cloud/global/images/centos-7-v20190116'
      zone: "{{ zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes: "{{ scopes }}"
      state: present
    register: disk

  - name: create an instance
    gcp_compute_instance:
      state: present
      name: compute-instance
      machine_type: n1-standard-1
      disks:
      - auto_delete: true
        boot: true
        source: "{{ disk }}"
      network_interfaces:
      - network: "{{ network }}"
        subnetwork: "{{ subnet }}"
        access_configs:
        - name: External NAT
          nat_ip: "{{ address }}"
          type: ONE_TO_ONE_NAT
      zone: "{{ zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes: "{{ scopes }}"
      tags:
        items:
        - apache-http-server
    register: instance

  - name: wait for ssh to come up
    wait_for:
      host: "{{ address.address }}"
      port: 22
      delay: 10
      timeout: 60

  - name: add host to host group
    add_host:
      hostname: "{{ address.address }}"
      groups: new_instances

- name: Manage new instances
  hosts: new_instances
  become: yes
  roles:
  - httpd
