---
- name: Delete GCP resources
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    gcp_project: ansible-gce-demo
    gcp_cred_kind: serviceaccount
    gcp_cred_file: ~/Documents/Personal/gcp_creds/ansible-gce-demo-a0dbb4ac2ff7.json
    zone: us-east1-b
    region: us-east1

  tasks:
  - name: delete an instance
    gcp_compute_instance:
      name: compute-instance
      zone: "{{ zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: absent

  # - name: delete a disk
  #   gcp_compute_disk:
  #     name: 'compute-disk'
  #     zone: "{{ zone }}"
  #     project: "{{ gcp_project }}"
  #     auth_kind: "{{ gcp_cred_kind }}"
  #     service_account_file: "{{ gcp_cred_file }}"
  #     state: absent

  - name: delete a firewall
    gcp_compute_firewall:
      name: 'compute-firewall'
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: absent

  - name: delete an address
    gcp_compute_address:
      name: 'compute-address'
      region: "{{ region }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: absent

  - name: delete a network
    gcp_compute_network:
      name: 'compute-network'
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: absent
