---
plugin: gcp_compute
zones:
 - us-east1-b
projects:
  - ansible-gce-demo
filters: []
groups:
  webservers: "'webserver' in name"
hostnames:
  - name
service_account_file: <path/to/your/service/account/key/file>.json
auth_kind: serviceaccount
